import { useEffect, useRef, useState } from "react";
import {
  Check,
  FileText,
  PenLine,
  Upload,
  UserRound,
  X,
  Trash2,
} from "lucide-react";

import { apiRequest } from "../../api/api";
import Toast from "../common/Toast";

// -----------------------------------------------------------------------------
// Patient Services
// -----------------------------------------------------------------------------

const SERVICE_OPTIONS = [
  { id: "patient-caretaker", name: "Patient Caretaker" },
  { id: "baby-caretaker", name: "Baby Caretaker" },
  { id: "japa-service", name: "Japa Service" },
  { id: "nurse", name: "Nurse" },
  { id: "baby-sitter", name: "Baby Sitter" },
  { id: "male-attendant", name: "Male Attendant" },
  { id: "elder-care", name: "Elder Care" },
  { id: "gnm-nurse", name: "GNM Nurse" },
  { id: "anm-nurse", name: "ANM Nurse" },
  { id: "bsc-nurse", name: "B.Sc Nurse" },
  { id: "icu-nurse", name: "ICU Nurse" },
];

// -----------------------------------------------------------------------------
// Empty Form
// -----------------------------------------------------------------------------

const EMPTY_FORM = {
  registrationNumber: "",
  firstName: "",
  middleName: "",
  lastName: "",

  dateOfBirth: "",
  age: "",

  gender: "",
  bloodGroup: "",

  phone: "",
  email: "",

  address: "",
  city: "",
  state: "",
  postalCode: "",

  emergencyContactName: "",
  emergencyContactPhone: "",
  emergencyContactRelation: "",

  occupation: "",
  maritalStatus: "",
  nationality: "",

  registrationDate: "",
  status: "Active",

  patientProblem: "",
  digitalSignature: "",
};

// -----------------------------------------------------------------------------
// Component
// -----------------------------------------------------------------------------

export default function PatientForm({
  patient = null,
  onSubmit,
  onClose,
  open = true,
  initialRegistrationNumber = "",
}) {
  const [form, setForm] = useState(EMPTY_FORM);

  const [selectedServices, setSelectedServices] =
    useState([]);

  const [toast, setToast] = useState({
    type: "success",
    title: "",
    message: "",
  });

  // Digital signature
  const signatureCanvasRef = useRef(null);
  const signatureInputRef = useRef(null);
  const isDrawingRef = useRef(false);

  const isEdit = Boolean(patient);

  // ---------------------------------------------------------------------------
  // Toast Helpers
  // ---------------------------------------------------------------------------

  const showToast = ({
    type = "success",
    title = "",
    message = "",
  }) => {
    setToast({
      type,
      title,
      message,
    });
  };

  const closeToast = () => {
    setToast({
      type: "success",
      title: "",
      message: "",
    });
  };

  // ---------------------------------------------------------------------------
  // Automatically hide form toast
  // ---------------------------------------------------------------------------

  useEffect(() => {
    if (!toast.message) return;

    const timer = setTimeout(() => {
      closeToast();
    }, 4000);

    return () => clearTimeout(timer);
  }, [toast.message]);

  // ---------------------------------------------------------------------------
  // Load Patient
  // ---------------------------------------------------------------------------

  useEffect(() => {
    if (!patient) {
      setForm({
        ...EMPTY_FORM,

        // Registration number is generated by backend.
        // Keep this empty for a new patient.
        registrationNumber: "",

        registrationDate:
          new Date()
            .toISOString()
            .split("T")[0],
      });

      setSelectedServices([]);

      // Clear canvas without modifying form state
      const canvas =
        signatureCanvasRef.current;

      if (canvas) {
        const context =
          canvas.getContext("2d");

        context?.clearRect(
          0,
          0,
          canvas.width,
          canvas.height
        );
      }

      return;
    }

    const patientServices =
      patient.services ||
      patient.serviceIds ||
      patient.patientServices ||
      [];

    const serviceIds = Array.isArray(
      patientServices
    )
      ? patientServices.map((service) =>
          typeof service === "string"
            ? service
            : service.id
        )
      : [];

    setForm({
      registrationNumber:
        patient.registrationNumber ||
        patient.registration_number ||
        "",

      firstName:
        patient.firstName ||
        patient.first_name ||
        "",

      middleName:
        patient.middleName ||
        patient.middle_name ||
        "",

      lastName:
        patient.lastName ||
        patient.last_name ||
        "",

      dateOfBirth:
        patient.dateOfBirth ||
        patient.date_of_birth ||
        "",

      age: patient.age ?? "",

      gender: patient.gender || "",

      bloodGroup:
        patient.bloodGroup ||
        patient.blood_group ||
        "",

      phone: patient.phone || "",

      email: patient.email || "",

      address: patient.address || "",

      city: patient.city || "",

      state: patient.state || "",

      postalCode:
        patient.postalCode ||
        patient.postal_code ||
        "",

      emergencyContactName:
        patient.emergencyContactName ||
        patient.emergency_contact_name ||
        "",

      emergencyContactPhone:
        patient.emergencyContactPhone ||
        patient.emergency_contact_phone ||
        "",

      emergencyContactRelation:
        patient.emergencyContactRelation ||
        patient.emergency_contact_relation ||
        "",

      occupation:
        patient.occupation || "",

      maritalStatus:
        patient.maritalStatus ||
        patient.marital_status ||
        "",

      nationality:
        patient.nationality || "",

      registrationDate:
        patient.registrationDate ||
        patient.registration_date ||
        new Date()
          .toISOString()
          .split("T")[0],

      status:
        patient.status || "Active",

      patientProblem:
        patient.patientProblem ||
        patient.patient_problem ||
        patient.problem ||
        patient.disease ||
        patient.reasonForRegistration ||
        "",

      digitalSignature:
        patient.digitalSignature ||
        patient.digital_signature ||
        patient.signature ||
        "",
    });

    setSelectedServices(serviceIds);
  }, [patient, initialRegistrationNumber]);

  // ---------------------------------------------------------------------------
  // Restore / Reset Signature Canvas
  // ---------------------------------------------------------------------------

  useEffect(() => {
    const timer = setTimeout(() => {
      const storedSignature =
        patient?.digitalSignature ||
        patient?.digital_signature ||
        patient?.signature;

      if (storedSignature) {
        drawStoredSignature(
          storedSignature
        );
      } else {
        const canvas =
          signatureCanvasRef.current;

        if (canvas) {
          const context =
            canvas.getContext("2d");

          context?.clearRect(
            0,
            0,
            canvas.width,
            canvas.height
          );
        }
      }
    }, 0);

    return () => clearTimeout(timer);
  }, [patient]);

  // ---------------------------------------------------------------------------
  // Form Change
  // ---------------------------------------------------------------------------

  const handleChange = (e) => {
    const { name, value } = e.target;

    setForm((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  // ---------------------------------------------------------------------------
  // Upload Digital Signature
  // ---------------------------------------------------------------------------

  const handleSignatureUpload = (event) => {
    const file =
      event.target.files?.[0];

    if (!file) return;

    const allowedTypes = [
      "image/png",
      "image/jpeg",
      "image/jpg",
      "image/webp",
    ];

    if (!allowedTypes.includes(file.type)) {
      showToast({
        type: "error",
        title: "Invalid Signature Format",
        message:
          "Please upload a PNG, JPG, JPEG, or WEBP signature image.",
      });

      event.target.value = "";
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      showToast({
        type: "error",
        title: "Signature Image Too Large",
        message:
          "Signature image must be less than 5 MB.",
      });

      event.target.value = "";
      return;
    }

    const reader = new FileReader();

    reader.onload = () => {
      const result = reader.result;

      setForm((prev) => ({
        ...prev,
        digitalSignature: result,
      }));

      drawStoredSignature(result);
    };

    reader.readAsDataURL(file);
  };

  // ---------------------------------------------------------------------------
  // Digital Signature
  // ---------------------------------------------------------------------------

  const getSignaturePosition = (
    event
  ) => {
    const canvas =
      signatureCanvasRef.current;

    if (!canvas) return null;

    const rect =
      canvas.getBoundingClientRect();

    const clientX =
      event.touches?.[0]?.clientX ??
      event.changedTouches?.[0]?.clientX ??
      event.clientX;

    const clientY =
      event.touches?.[0]?.clientY ??
      event.changedTouches?.[0]?.clientY ??
      event.clientY;

    return {
      x:
        ((clientX - rect.left) /
          rect.width) *
        canvas.width,

      y:
        ((clientY - rect.top) /
          rect.height) *
        canvas.height,
    };
  };

  const startSignature = (event) => {
    event.preventDefault();

    const canvas =
      signatureCanvasRef.current;

    const position =
      getSignaturePosition(event);

    if (!canvas || !position) return;

    const context =
      canvas.getContext("2d");

    if (!context) return;

    isDrawingRef.current = true;

    context.beginPath();

    context.moveTo(
      position.x,
      position.y
    );
  };

  const drawSignature = (event) => {
    if (!isDrawingRef.current)
      return;

    event.preventDefault();

    const canvas =
      signatureCanvasRef.current;

    const position =
      getSignaturePosition(event);

    if (!canvas || !position)
      return;

    const context =
      canvas.getContext("2d");

    if (!context) return;

    context.lineWidth = 2.2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.strokeStyle = "#173F41";

    context.lineTo(
      position.x,
      position.y
    );

    context.stroke();
  };

  const endSignature = () => {
    if (!isDrawingRef.current)
      return;

    isDrawingRef.current = false;

    const canvas =
      signatureCanvasRef.current;

    if (!canvas) return;

    setForm((prev) => ({
      ...prev,
      digitalSignature:
        canvas.toDataURL("image/png"),
    }));
  };

  const clearSignatureCanvas = () => {
    const canvas =
      signatureCanvasRef.current;

    if (canvas) {
      const context =
        canvas.getContext("2d");

      if (context) {
        context.clearRect(
          0,
          0,
          canvas.width,
          canvas.height
        );
      }
    }

    setForm((prev) => ({
      ...prev,
      digitalSignature: "",
    }));
  };

  const drawStoredSignature = (
    signature
  ) => {
    const canvas =
      signatureCanvasRef.current;

    if (!canvas || !signature) {
      if (canvas) {
        const context =
          canvas.getContext("2d");

        context?.clearRect(
          0,
          0,
          canvas.width,
          canvas.height
        );
      }

      return;
    }

    const image = new Image();

    image.onload = () => {
      const context =
        canvas.getContext("2d");

      if (!context) return;

      context.clearRect(
        0,
        0,
        canvas.width,
        canvas.height
      );

      context.drawImage(
        image,
        0,
        0,
        canvas.width,
        canvas.height
      );

      setForm((prev) => ({
        ...prev,
        digitalSignature: signature,
      }));
    };

    image.src = signature;
  };

  // ---------------------------------------------------------------------------
  // Service Selection
  // ---------------------------------------------------------------------------

  const toggleService = (
    serviceId
  ) => {
    setSelectedServices((prev) =>
      prev.includes(serviceId)
        ? prev.filter(
            (id) => id !== serviceId
          )
        : [...prev, serviceId]
    );
  };

  // ---------------------------------------------------------------------------
  // Submit
  // ---------------------------------------------------------------------------

  const handleSubmit = async (e) => {
    e.preventDefault();

    const trimmedProblem =
      form.patientProblem.trim();

    // Patient problem validation
    if (!trimmedProblem) {
      showToast({
        type: "error",
        title: "Missing Patient Problem",
        message:
          "Please enter the patient's problem, disease, symptoms, or reason for registration.",
      });

      return;
    }

    // -------------------------------------------------------
    // Registration number
    //
    // IMPORTANT:
    // New patient:
    // Backend generates the registration number.
    //
    // Existing patient:
    // Existing registration number is sent for update.
    // -------------------------------------------------------

    const registrationNumber =
      form.registrationNumber.trim();

    const fullName = [
      form.firstName,
      form.middleName,
      form.lastName,
    ]
      .filter(Boolean)
      .join(" ")
      .trim();

    const patientData = {
      first_name:
        form.firstName.trim(),

      middle_name:
        form.middleName.trim() ||
        null,

      last_name:
        form.lastName.trim() ||
        null,

      date_of_birth:
        form.dateOfBirth || null,

      age:
        form.age === ""
          ? null
          : Number(form.age),

      gender:
        form.gender,

      blood_group:
        form.bloodGroup || null,

      phone:
        form.phone.trim(),

      email:
        form.email.trim() || null,

      address:
        form.address.trim() || null,

      city:
        form.city.trim() || null,

      state:
        form.state.trim() || null,

      postal_code:
        form.postalCode.trim() ||
        null,

      emergency_contact_name:
        form.emergencyContactName.trim() ||
        null,

      emergency_contact_phone:
        form.emergencyContactPhone.trim() ||
        null,

      emergency_contact_relation:
        form.emergencyContactRelation.trim() ||
        null,

      occupation:
        form.occupation.trim() ||
        null,

      marital_status:
        form.maritalStatus || null,

      nationality:
        form.nationality.trim() ||
        null,

      registration_date:
        form.registrationDate || null,

      status:
        form.status || "Active",

      patient_problem:
        trimmedProblem,

      digital_signature:
        form.digitalSignature || null,
    };

    // -------------------------------------------------------
    // Only send registration_number when editing.
    //
    // For a new patient, the backend generates it.
    // -------------------------------------------------------

    if (isEdit && registrationNumber) {
      patientData.registration_number =
        registrationNumber;
    }

    try {
      let data;

      // -----------------------------------------------------
      // EDIT EXISTING PATIENT
      // -----------------------------------------------------

      if (isEdit) {
        data = await apiRequest(
          `/patients/${patient.id}`,
          {
            method: "PUT",
            body: JSON.stringify(
              patientData
            ),
          }
        );
      }

      // -----------------------------------------------------
      // CREATE NEW PATIENT
      // -----------------------------------------------------

      else {
        data = await apiRequest(
          "/patients/",
          {
            method: "POST",
            body: JSON.stringify(
              patientData
            ),
          }
        );
      }

      console.log(
        isEdit
          ? "Patient updated:"
          : "Patient created:",
        data
      );

      // -----------------------------------------------------
      // Backend-generated registration number
      //
      // The backend may return something like:
      // PAT-0001
      // PAT-0002
      // PAT-0003
      // -----------------------------------------------------

      const generatedRegistrationNumber =
        data?.registration_number ||
        data?.registrationNumber ||
        "";

      // -----------------------------------------------------
      // Selected services
      // -----------------------------------------------------

      const selectedServiceObjects =
        SERVICE_OPTIONS.filter(
          (service) =>
            selectedServices.includes(
              service.id
            )
        );

      // -----------------------------------------------------
      // Send result to parent.
      //
      // Patients.jsx handles:
      // - refreshing patient list
      // - success toast
      // - closing modal
      // -----------------------------------------------------

      onSubmit?.({
        ...data,

        // Use backend-generated number
        // if available.
        registrationNumber:
          generatedRegistrationNumber ||
          registrationNumber,

        fullName,
        name: fullName,

        services:
          selectedServiceObjects,

        serviceIds:
          selectedServices,
      });

      // Do NOT close the form here.
      //
      // The parent Patients.jsx will close
      // the modal after it updates its state.
    } catch (error) {
      console.error(
        isEdit
          ? "Patient update failed:"
          : "Patient registration failed:",
        error
      );

      showToast({
        type: "error",
        title: isEdit
          ? "Update Failed"
          : "Registration Failed",
        message:
          error.message ||
          (isEdit
            ? "Failed to update patient."
            : "Failed to register patient."),
      });
    }
  };

  // ---------------------------------------------------------------------------
  // If Closed
  // ---------------------------------------------------------------------------

  if (!open) {
    return null;
  }

  // ---------------------------------------------------------------------------
  // UI
  // ---------------------------------------------------------------------------

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-2.5 backdrop-blur-sm sm:p-4 md:p-6">

      {/* Toast */}

      <Toast
        type={toast.type}
        title={toast.title}
        message={toast.message}
        onClose={closeToast}
      />

      <div className="flex max-h-[95vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl sm:rounded-3xl">

        {/* ----------------------------------------------------------------
            Header
        ---------------------------------------------------------------- */}

        <div className="flex shrink-0 items-center justify-between border-b border-[#E2EFED] px-4 py-3 sm:px-6 sm:py-4">
          <div>
            <h2 className="text-base font-bold text-[#173F41] sm:text-lg md:text-xl">
              {isEdit
                ? "Edit Patient"
                : "Register New Patient"}
            </h2>

            <p className="mt-0.5 text-xs text-[#819596] sm:text-sm">
              {isEdit
                ? "Update patient information and services"
                : "Enter patient information for registration"}
            </p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-lg text-[#819596] transition hover:bg-[#E8F8F6] hover:text-[#078E89]"
          >
            <X size={18} />
          </button>
        </div>

        {/* ----------------------------------------------------------------
            Form
        ---------------------------------------------------------------- */}

        <form
          onSubmit={handleSubmit}
          className="min-h-0 flex-1 overflow-y-auto"
        >
          <div className="space-y-6 p-6">

            {/* ============================================================
                Patient Information
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <UserRound size={18} />
                }
                title="Patient Information"
              />

              <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">

                <InputField
                  label="Registration Number"
                  name="registrationNumber"
                  value={
                    form.registrationNumber
                  }
                  onChange={
                    handleChange
                  }
                  placeholder={
                    isEdit
                      ? "Registration number"
                      : "Generated by backend"
                  }
                  readOnly={true}
                />

                <InputField
                  label="First Name"
                  name="firstName"
                  value={form.firstName}
                  onChange={handleChange}
                  placeholder="Enter first name"
                  required
                />

                <InputField
                  label="Middle Name"
                  name="middleName"
                  value={form.middleName}
                  onChange={handleChange}
                  placeholder="Enter middle name"
                />

                <InputField
                  label="Last Name"
                  name="lastName"
                  value={form.lastName}
                  onChange={handleChange}
                  placeholder="Enter last name"
                />

                <InputField
                  label="Date of Birth"
                  name="dateOfBirth"
                  type="date"
                  value={
                    form.dateOfBirth
                  }
                  onChange={
                    handleChange
                  }
                />

                <InputField
                  label="Age"
                  name="age"
                  type="number"
                  min="0"
                  max="150"
                  value={form.age}
                  onChange={
                    handleChange
                  }
                  placeholder="Enter age"
                />

                <SelectField
                  label="Gender"
                  name="gender"
                  value={form.gender}
                  onChange={
                    handleChange
                  }
                  options={[
                    {
                      value: "Male",
                      label: "Male",
                    },
                    {
                      value: "Female",
                      label: "Female",
                    },
                    {
                      value: "Other",
                      label: "Other",
                    },
                  ]}
                />

                <SelectField
                  label="Blood Group"
                  name="bloodGroup"
                  value={
                    form.bloodGroup
                  }
                  onChange={
                    handleChange
                  }
                  options={[
                    {
                      value: "A+",
                      label: "A+",
                    },
                    {
                      value: "A-",
                      label: "A-",
                    },
                    {
                      value: "B+",
                      label: "B+",
                    },
                    {
                      value: "B-",
                      label: "B-",
                    },
                    {
                      value: "AB+",
                      label: "AB+",
                    },
                    {
                      value: "AB-",
                      label: "AB-",
                    },
                    {
                      value: "O+",
                      label: "O+",
                    },
                    {
                      value: "O-",
                      label: "O-",
                    },
                  ]}
                />

                <SelectField
                  label="Marital Status"
                  name="maritalStatus"
                  value={
                    form.maritalStatus
                  }
                  onChange={
                    handleChange
                  }
                  options={[
                    {
                      value: "Single",
                      label: "Single",
                    },
                    {
                      value: "Married",
                      label: "Married",
                    },
                    {
                      value: "Divorced",
                      label: "Divorced",
                    },
                    {
                      value: "Widowed",
                      label: "Widowed",
                    },
                    {
                      value: "Separated",
                      label: "Separated",
                    },
                  ]}
                />

                <InputField
                  label="Occupation"
                  name="occupation"
                  value={
                    form.occupation
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter occupation"
                />

                <InputField
                  label="Nationality"
                  name="nationality"
                  value={
                    form.nationality
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter nationality"
                />
              </div>
            </section>

            {/* ============================================================
                Patient Problem / Disease
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <FileText size={18} />
                }
                title="Patient Problem / Disease"
              />

              <div className="mt-4">
                <TextAreaField
                  label="Problem / Disease / Reason for Registration"
                  name="patientProblem"
                  value={
                    form.patientProblem
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter the patient's disease, symptoms, injury, treatment requirement, health problem, or reason for registration..."
                  required
                  rows={4}
                />

                <p className="mt-2 text-xs text-[#819596]">
                  Record why the patient is
                  being registered. This can
                  include a known disease,
                  symptoms, injury, treatment
                  requirement, or other
                  health-related reason.
                </p>
              </div>
            </section>

            {/* ============================================================
                Contact Information
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <UserRound size={18} />
                }
                title="Contact Information"
              />

              <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">

                <InputField
                  label="Phone"
                  name="phone"
                  type="tel"
                  value={form.phone}
                  onChange={
                    handleChange
                  }
                  placeholder="Enter phone number"
                />

                <InputField
                  label="Email"
                  name="email"
                  type="email"
                  value={form.email}
                  onChange={
                    handleChange
                  }
                  placeholder="Enter email address"
                />

                <div className="md:col-span-2">
                  <TextAreaField
                    label="Address"
                    name="address"
                    value={
                      form.address
                    }
                    onChange={
                      handleChange
                    }
                    placeholder="Enter complete address"
                    rows={3}
                  />
                </div>

                <InputField
                  label="City"
                  name="city"
                  value={form.city}
                  onChange={
                    handleChange
                  }
                  placeholder="Enter city"
                />

                <InputField
                  label="State"
                  name="state"
                  value={form.state}
                  onChange={
                    handleChange
                  }
                  placeholder="Enter state"
                />

                <InputField
                  label="Postal Code"
                  name="postalCode"
                  value={
                    form.postalCode
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter postal code"
                />
              </div>
            </section>

            {/* ============================================================
                Emergency Contact
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <UserRound size={18} />
                }
                title="Emergency Contact"
              />

              <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">

                <InputField
                  label="Contact Name"
                  name="emergencyContactName"
                  value={
                    form.emergencyContactName
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter contact name"
                />

                <InputField
                  label="Contact Phone"
                  name="emergencyContactPhone"
                  type="tel"
                  value={
                    form.emergencyContactPhone
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="Enter contact phone"
                />

                <InputField
                  label="Relation"
                  name="emergencyContactRelation"
                  value={
                    form.emergencyContactRelation
                  }
                  onChange={
                    handleChange
                  }
                  placeholder="e.g. Father, Mother, Spouse"
                />
              </div>
            </section>

            {/* ============================================================
                Digital Signature
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <PenLine size={18} />
                }
                title="Digital Signature"
              />

              <div className="mt-4 space-y-3">

                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">

                  <p className="text-xs text-[#819596]">
                    Draw your signature below
                    or upload an existing
                    signature image.
                  </p>

                  <div className="flex flex-wrap gap-2">

                    <input
                      ref={
                        signatureInputRef
                      }
                      type="file"
                      accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp"
                      onChange={
                        handleSignatureUpload
                      }
                      className="hidden"
                    />

                    <button
                      type="button"
                      onClick={() =>
                        signatureInputRef.current?.click()
                      }
                      className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-[#E2EFED] bg-white px-3.5 text-xs font-semibold text-[#31585A] transition hover:border-[#08A6A0] hover:bg-[#E8F8F6] hover:text-[#078E89]"
                    >
                      <Upload size={15} />
                      Upload Signature
                    </button>

                    <button
                      type="button"
                      onClick={
                        clearSignatureCanvas
                      }
                      className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-red-200 px-3.5 text-xs font-semibold text-red-600 transition hover:bg-red-50"
                    >
                      <Trash2 size={15} />
                      Clear
                    </button>

                  </div>
                </div>

                <div className="overflow-hidden rounded-xl border border-[#E2EFED] bg-[#FAFDFC]">

                  <canvas
                    ref={
                      signatureCanvasRef
                    }
                    width={900}
                    height={260}
                    onMouseDown={
                      startSignature
                    }
                    onMouseMove={
                      drawSignature
                    }
                    onMouseUp={
                      endSignature
                    }
                    onMouseLeave={
                      endSignature
                    }
                    onTouchStart={
                      startSignature
                    }
                    onTouchMove={
                      drawSignature
                    }
                    onTouchEnd={
                      endSignature
                    }
                    className="block h-44 w-full cursor-crosshair touch-none bg-white sm:h-52 md:h-56"
                  />

                </div>

                <div className="flex items-center gap-2 text-xs text-[#819596]">

                  <PenLine
                    size={14}
                    className="shrink-0 text-[#08A6A0]"
                  />

                  <span>
                    Draw inside the box
                    using your mouse,
                    trackpad, or touchscreen.
                  </span>

                </div>

                <p className="text-[11px] text-[#819596]">
                  Upload formats: PNG, JPG,
                  JPEG, WEBP. Maximum size:
                  5 MB.
                </p>

              </div>
            </section>

            {/* ============================================================
                Registration
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <Check size={18} />
                }
                title="Registration"
              />

              <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">

                <InputField
                  label="Registration Date"
                  name="registrationDate"
                  type="date"
                  value={
                    form.registrationDate
                  }
                  onChange={
                    handleChange
                  }
                />

                <SelectField
                  label="Status"
                  name="status"
                  value={form.status}
                  onChange={
                    handleChange
                  }
                  options={[
                    {
                      value: "Active",
                      label: "Active",
                    },
                    {
                      value: "Inactive",
                      label: "Inactive",
                    },
                    {
                      value: "Deceased",
                      label: "Deceased",
                    },
                  ]}
                />

              </div>
            </section>

            {/* ============================================================
                Patient Services
            ============================================================ */}

            <section>
              <SectionTitle
                icon={
                  <Check size={18} />
                }
                title="Patient Services"
              />

              <p className="mt-1 text-sm text-[#819596]">
                Select the services required
                by this patient.
              </p>

              <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">

                {SERVICE_OPTIONS.map(
                  (service) => {
                    const selected =
                      selectedServices.includes(
                        service.id
                      );

                    return (
                      <button
                        key={service.id}
                        type="button"
                        onClick={() =>
                          toggleService(
                            service.id
                          )
                        }
                        className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${
                          selected
                            ? "border-[#08A6A0] bg-[#E8F8F6]"
                            : "border-[#E2EFED] bg-white hover:border-[#08A6A0] hover:bg-[#FAFDFC]"
                        }`}
                      >

                        <span
                          className={`flex h-5 w-5 shrink-0 items-center justify-center rounded border ${
                            selected
                              ? "border-[#08A6A0] bg-[#08A6A0] text-white"
                              : "border-[#B7C8C8] bg-white"
                          }`}
                        >
                          {selected && (
                            <Check size={13} />
                          )}
                        </span>

                        <span
                          className={`text-sm font-medium ${
                            selected
                              ? "text-[#078E89]"
                              : "text-[#31585A]"
                          }`}
                        >
                          {service.name}
                        </span>

                      </button>
                    );
                  }
                )}

              </div>

              {selectedServices.length >
                0 && (
                <div className="mt-4 rounded-lg bg-[#E8F8F6] px-4 py-3 text-sm text-[#31585A]">

                  <span className="font-semibold text-[#078E89]">
                    {
                      selectedServices.length
                    }
                  </span>{" "}
                  service
                  {selectedServices.length !==
                  1
                    ? "s"
                    : ""}{" "}
                  selected

                </div>
              )}

            </section>
          </div>

          {/* ----------------------------------------------------------------
              Footer
          ---------------------------------------------------------------- */}

          <div className="sticky bottom-0 flex shrink-0 items-center justify-end gap-2.5 border-t border-[#E2EFED] bg-white px-4 py-3 sm:gap-3 sm:px-6 sm:py-4">

            <button
              type="button"
              onClick={onClose}
              className="h-10 rounded-xl border border-[#E2EFED] bg-white px-4 text-xs font-semibold text-[#31585A] transition hover:bg-[#E8F8F6] sm:h-11 sm:px-5 sm:text-sm"
            >
              Cancel
            </button>

            <button
              type="submit"
              className="inline-flex h-10 items-center justify-center gap-1.5 rounded-xl bg-[#08A6A0] px-4 text-xs font-semibold text-white transition hover:bg-[#078E89] sm:h-11 sm:gap-2 sm:px-5 sm:text-sm"
            >
              <Check size={16} />

              {isEdit
                ? "Update Patient"
                : "Register Patient"}
            </button>

          </div>
        </form>
      </div>
    </div>
  );
}

// ============================================================================
// Section Title
// ============================================================================

function SectionTitle({
  icon,
  title,
}) {
  return (
    <div className="flex items-center gap-2 border-b border-[#E2EFED] pb-2.5 sm:pb-3">

      <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#E8F8F6] text-[#08A6A0] sm:h-8 sm:w-8">
        {icon}
      </div>

      <h3 className="text-sm font-bold text-[#173F41] sm:text-base">
        {title}
      </h3>

    </div>
  );
}

// ============================================================================
// Input Field
// ============================================================================

function InputField({
  label,
  name,
  type = "text",
  value,
  onChange,
  placeholder = "",
  required = false,
  min,
  max,
  readOnly = false,
}) {
  return (
    <div>

      <label
        htmlFor={name}
        className="mb-1.5 block text-xs font-semibold text-[#31585A] sm:text-sm"
      >
        {label}

        {required && (
          <span className="ml-1 text-red-500">
            *
          </span>
        )}
      </label>

      <input
        id={name}
        name={name}
        type={type}
        value={value ?? ""}
        onChange={onChange}
        placeholder={placeholder}
        required={required}
        min={min}
        max={max}
        readOnly={readOnly}
        className={`h-10 w-full rounded-xl border border-[#E2EFED] bg-[#FAFDFC] px-3 text-xs text-[#173F41] outline-none transition placeholder:text-[#A0B1B1] focus:border-[#08A6A0] focus:ring-2 focus:ring-[#08A6A0]/10 sm:h-11 sm:px-3.5 sm:text-sm ${
          readOnly
            ? "cursor-not-allowed bg-[#F1F7F6] text-[#527173]"
            : ""
        }`}
      />

    </div>
  );
}

// ============================================================================
// Select Field
// ============================================================================

function SelectField({
  label,
  name,
  value,
  onChange,
  options = [],
  required = false,
}) {
  return (
    <div>

      <label
        htmlFor={name}
        className="mb-1.5 block text-xs font-semibold text-[#31585A] sm:text-sm"
      >
        {label}

        {required && (
          <span className="ml-1 text-red-500">
            *
          </span>
        )}
      </label>

      <select
        id={name}
        name={name}
        value={value ?? ""}
        onChange={onChange}
        required={required}
        className="h-10 w-full rounded-xl border border-[#E2EFED] bg-[#FAFDFC] px-3 text-xs text-[#173F41] outline-none transition focus:border-[#08A6A0] focus:ring-2 focus:ring-[#08A6A0]/10 sm:h-11 sm:px-3.5 sm:text-sm"
      >
        <option value="">
          Select {label.toLowerCase()}
        </option>

        {options.map((option) => (
          <option
            key={option.value}
            value={option.value}
          >
            {option.label}
          </option>
        ))}
      </select>

    </div>
  );
}

// ============================================================================
// Text Area Field
// ============================================================================

function TextAreaField({
  label,
  name,
  value,
  onChange,
  placeholder,
  rows = 3,
  required = false,
}) {
  return (
    <div>

      <label
        htmlFor={name}
        className="mb-1.5 block text-xs font-semibold text-[#31585A] sm:text-sm"
      >
        {label}

        {required && (
          <span className="ml-1 text-red-500">
            *
          </span>
        )}
      </label>

      <textarea
        id={name}
        name={name}
        value={value ?? ""}
        onChange={onChange}
        placeholder={placeholder}
        rows={rows}
        required={required}
        className="w-full resize-none rounded-xl border border-[#E2EFED] bg-[#FAFDFC] px-3 py-2 text-xs text-[#173F41] outline-none transition placeholder:text-[#A0B1B1] focus:border-[#08A6A0] focus:ring-2 focus:ring-[#08A6A0]/10 sm:px-3.5 sm:py-2.5 sm:text-sm"
      />

    </div>
  );
}